# Generated by Django 2.1.2 on 2018-11-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='roomType',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, 'Full Property'), (2, 'Room')], default=0, help_text='Room Type Full Property/Room'),
        ),
    ]
