# Generated by Django 2.1.2 on 2018-11-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='publicName',
            field=models.CharField(default='Nickname', help_text='Listing Nickname', max_length=200),
        ),
    ]
