# Generated by Django 2.1.2 on 2018-11-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_publicname'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='breakfastFee',
            field=models.IntegerField(help_text='breakfast fee', null=True),
        ),
    ]
