# Generated by Django 2.1.2 on 2018-11-05 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import src.core.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0002_listing_roomtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=src.core.utils.asset_upload_property)),
                ('normal', models.ImageField(blank=True, null=True, upload_to=src.core.utils.asset_upload_property)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField(auto_now=True, help_text='Day of creations', null=True)),
                ('lastUpdatedAt', models.DateField(auto_now=True, help_text='Last updated Day', null=True)),
                ('confirmationCode', models.CharField(help_text='Confirmation Code exp C001', max_length=50, null=True)),
                ('checkIn', models.DateField(help_text='Day of entrance', null=True)),
                ('checkOut', models.DateField(help_text='Day leaving the listing', null=True)),
                ('nightsCount', models.IntegerField(help_text='Amount of nights', null=True)),
                ('daysInAdvance', models.IntegerField(help_text='Days in Advance of the booking', null=True)),
                ('guestsCount', models.IntegerField(help_text='Amount of guest to recieve', null=True)),
                ('status', models.IntegerField(choices=[(0, 'inquiry'), (1, 'declined'), (2, 'expired'), (3, 'canceled'), (4, 'reserved'), (5, 'confirmed'), (6, 'Awaiting for Payment')], default=0, help_text='Status')),
                ('guest', models.OneToOneField(help_text='reference to de client', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='listing',
            name='picture',
            field=models.OneToOneField(help_text='Main listing Picture', null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.PictureListing'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='listing',
            field=models.OneToOneField(help_text='listing booked', null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.Listing'),
        ),
    ]
