# Generated by Django 2.1.2 on 2018-11-05 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20181105_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full', models.CharField(help_text='Full address', max_length=250, null=True)),
                ('lng', models.FloatField(help_text='Geo Longitude', null=True)),
                ('lat', models.FloatField(help_text='Geo Latitude', null=True)),
                ('street', models.CharField(help_text='Street', max_length=200, null=True)),
                ('city', models.CharField(help_text='City', max_length=200, null=True)),
                ('country', models.CharField(help_text='Country', max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='listing',
            name='address',
            field=models.OneToOneField(help_text='Listing Address', null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.Address'),
        ),
    ]
