# Generated by Django 2.1.2 on 2018-12-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='picture',
            new_name='portrait',
        ),
        migrations.AlterField(
            model_name='price',
            name='basePrice',
            field=models.FloatField(default=0, help_text='Base Price'),
        ),
        migrations.AlterField(
            model_name='price',
            name='breakfastFee',
            field=models.FloatField(help_text='breakfast fee', null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='extraPersonFee',
            field=models.FloatField(default=0, help_text='Extra person Fee'),
        ),
    ]
