# Generated by Django 2.1.2 on 2018-11-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20181105_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='pictures',
            field=models.ManyToManyField(help_text='Pictures Gallery', related_name='pictures', to='listings.PictureListing'),
        ),
    ]
