# Generated by Django 2.1.2 on 2018-12-04 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20181204_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='pictures',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='portrait',
        ),
        migrations.AddField(
            model_name='picturelisting',
            name='is_portrait',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='picturelisting',
            name='listing',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='listings.Listing'),
        ),
    ]
