# Generated by Django 2.1.2 on 2018-10-17 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import src.users.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=src.users.utils.asset_upload)),
                ('normal', models.ImageField(blank=True, null=True, upload_to=src.users.utils.asset_upload)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('U', 'unknown'), ('M', 'male'), ('F', 'female')], default='U', max_length=1, null=True, verbose_name='gender')),
                ('emails', models.ManyToManyField(blank=True, help_text='The emails this user has configured.', related_name='email_set', related_query_name='user_profile', to='users.Email', verbose_name='emails')),
                ('picture', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.Picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
