# Generated by Django 2.1.2 on 2018-10-17 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181017_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='emails',
        ),
        migrations.AddField(
            model_name='email',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.OneToOneField(blank=True, help_text='User Avatar and Picture', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Picture', verbose_name='picture'),
        ),
    ]
