# Generated by Django 2.1.2 on 2018-11-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full', models.CharField(help_text='Full address', max_length=250, null=True)),
                ('lng', models.FloatField(help_text='Geo Longitude', null=True)),
                ('lat', models.FloatField(help_text='Geo Latitude', null=True)),
                ('street', models.CharField(help_text='Street', max_length=200, null=True)),
                ('city', models.CharField(help_text='City', max_length=200, null=True)),
                ('country', models.CharField(help_text='Country', max_length=200, null=True)),
            ],
        ),
    ]
