# Generated by Django 2.1.2 on 2018-11-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Country Code', max_length=10, null=True)),
                ('name', models.CharField(help_text='Country Name', max_length=30, null=True)),
            ],
        ),
    ]
