# Generated by Django 2.1.2 on 2018-11-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(help_text='Currency Code example EUR', max_length=5, null=True),
        ),
    ]
