# Generated by Django 2.1.2 on 2018-11-05 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20181105_1036'),
        ('core', '0002_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
